### ISSUE TITLE
Does not work at all on funtoo. 

### ISSUE THREAD

**Issue by michaelmrose** [m-click/mcpdf#14]
Readme is woefully incomplete as far as what part of pdftk functionality it supports and its clear it doesn't support near the functionality.

No man page

No --help -h

I am incredibly disappointed that funtoo has replaced a long working app with what I perceive as a sophmoric effort by a coder too unprofessional even to provide guidance on how to use it.

Nobody on earth wants to read the source to your crummy java app in order to figure out how to use it.

**Comment by michaelmrose** [comment]
Please see https://bugs.funtoo.org/browse/FL-970

**Comment by vog** [comment]
@michaelmrose It seems that the project description raised false expectations. We will fix that.

However, please reconsider your tone. Everybody wants a PDFtk replacement, but nobody wants to implement that. You just managed to put down people for working on that vision.

PDFtk is based on a very old version of the itextpdf Java library. We need a PDFtk replacement that is based on a more recent version of the itextpdf library, and is written in pure Java rather than a mix of C++ and Java. As far as I can tell, many people share this view. This project aims to bring these people together.

Note that Mcpdf's version currently is at 0.2.3, which is by any measure far away from a 1.0 release.

Volunteers are welcome!

**Comment by michaelmrose** [comment]
In 20 months this project has accumulated generously 1 day of code and it does virtually nothing. At this point it's really version 0.0.1 It actually probably took as much effort to create the github. 

At this point it will be finished in time for the heat death of the universe.
