### ISSUE TITLE
Missing character after filling

### ISSUE THREAD

**Issue by michalCapo** [m-click/mcpdf#25]
After filling pdf form, there are some missing characters. I spent very long time figuring this issue, but no luck. Could you please investigate?
```
java -jar mcpdf-0.2.4-jar-with-dependencies.jar a.pdf fill_form - output - < a.xfdf > b.pdf
```
[missing_characters.zip](https://github.com/m-click/mcpdf/files/4452412/missing_characters.zip)

**Comment by vog** [comment]
Thanks for your report. Please note that Mcpdf is essentially a wrapper around the [iText PDF Library](http://itextpdf.com/product/itext). Your issue seems to be a bug in that library.

As a first step, you can try to combine Mcpdf with a newer version of this library, as described in our README:

* https://github.com/m-click/mcpdf#combine-with-another-library-version

If that doesn't help, please report this issue to the library's  authors:

* [iText PDF Library](http://itextpdf.com/product/itext)

I'm closing this issue for now, as it is out of scope of this project. Nevertheless, feel free to report any finding you have back here.

**Comment by michalCapo** [comment]
It seems to be iText PDF problem
